server:
  port: 5000
spring: 
  management:
    security:
      enabled: false
  security: 
    user: 
      name: hoob
      password: hoobzhu
  basic: 
    enabled: false
  endpoints: 
    health: 
      sensitive: true
  boot: 
    admin: 
      url: http://localhost:5000
  #配置是否开启权限认证标识
  profiles:
    active: secure   #insecure 不开启鉴权
    include: secure
  application:
    name: microservice-admin
  redis: 
    host: 127.0.0.1
    port: 6379
  cloud: 
    config:
      profile: dev 
      label: master
      discovery:
        enabled: true
        service-id:  config-server
  rabbitmq: 
    host: localhost
    port: 5672
    username: hoob
    password: zhuqinhe
eureka:
  client:
    service-url:
      defaultZone: http://hoob:hoobzhu@localhost:8761/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${spring.application.instance_id:${server.port}}
    lease-renewal-interval-in-seconds: 30 #eureka客户端需要向eureka服务器发送心跳以指示它仍然存在的频率（以秒为单位）默认30 ，生成环境不建议修改

management:                  
  endpoints: 
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always     
